server:
  port: 8080

spring:
  datasource:
    hikari:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:mem:testdb;MODE=MYSQL;DATABASE_TO_LOWER=TRUE
      username: sa
      password:
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

  servlet:
    multipart:
      enabled: true

logging:
  file:
    name: C:\Users\JINA\IdeaProjects\excelEdit\log\
  level:
    com:
      daily:
        report:
          excel: debug
